### ISSUE TITLE
issue when running the keyclockowinauthentication application

### ISSUE THREAD

**Issue by vinothramanathan** [dylanplecki/KeycloakOwinAuthentication#24] opened 2016-01-14 12:55 UTC
Issue when running the application.

please find the debug error list.

Please help me to solve the issue.

Error	51	'KeycloakIdentityModel.KeycloakIdentity._accessToken' is a 'field' but is used like a 'type'	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	54	70	KeycloakIdentityModel
Error	50	'KeycloakIdentityModel.KeycloakIdentity._kcClaims' is a 'field' but is used like a 'type'	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	54	49	KeycloakIdentityModel
Error	49	'KeycloakIdentityModel.KeycloakIdentity._parameters' is a 'field' but is used like a 'type'	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	49	54	KeycloakIdentityModel
Error	86	'KeycloakIdentityModel.Utilities.ClaimMapping.ClaimMappings' does not contain a definition for 'IdTokenMappings'	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	402	94	KeycloakIdentityModel
Error	87	'KeycloakIdentityModel.Utilities.ClaimMapping.ClaimMappings' does not contain a definition for 'RefreshTokenMappings'	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	413	90	KeycloakIdentityModel
Error	52	'System.DateTime.Now' is a 'property' but is used like a 'type'	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	54	102	KeycloakIdentityModel
Error	1	; expected	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	49	51	KeycloakIdentityModel
Error	3	; expected	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	54	46	KeycloakIdentityModel
Error	16	A namespace cannot directly contain members such as fields or methods	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	17	14	KeycloakIdentityModel
Error	69	Cannot await in the body of a catch clause	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	250	17	KeycloakIdentityModel
Error	17	Expected class, delegate, enum, interface, or struct	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	18	17	KeycloakIdentityModel
Error	18	Expected class, delegate, enum, interface, or struct	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	23	17	KeycloakIdentityModel
Error	19	Expected class, delegate, enum, interface, or struct	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	30	17	KeycloakIdentityModel
Error	20	Expected class, delegate, enum, interface, or struct	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	37	17	KeycloakIdentityModel
Error	21	Expected class, delegate, enum, interface, or struct	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	42	17	KeycloakIdentityModel
Error	22	Expected class, delegate, enum, interface, or struct	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	47	17	KeycloakIdentityModel
Error	23	Expected class, delegate, enum, interface, or struct	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	52	17	KeycloakIdentityModel
Error	24	Expected class, delegate, enum, interface, or struct	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	57	17	KeycloakIdentityModel
Error	25	Expected class, delegate, enum, interface, or struct	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	62	17	KeycloakIdentityModel
Error	26	Expected class, delegate, enum, interface, or struct	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	69	23	KeycloakIdentityModel
Error	27	Expected class, delegate, enum, interface, or struct	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	69	79	KeycloakIdentityModel
Error	28	Expected class, delegate, enum, interface, or struct	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	71	23	KeycloakIdentityModel
Error	29	Expected class, delegate, enum, interface, or struct	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	71	84	KeycloakIdentityModel
Error	30	Expected class, delegate, enum, interface, or struct	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	73	17	KeycloakIdentityModel
Error	4	Invalid token '!=' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	54	59	KeycloakIdentityModel
Error	12	Invalid token '(' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimLookup.cs	14	84	KeycloakIdentityModel
Error	37	Invalid token '(' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Models\Configuration\DefaultKeycloakParameters.cs	108	76	KeycloakIdentityModel
Error	40	Invalid token '(' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Models\Configuration\DefaultKeycloakParameters.cs	129	85	KeycloakIdentityModel
Error	14	Invalid token ',' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	15	58	KeycloakIdentityModel
Error	2	Invalid token ';' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	49	84	KeycloakIdentityModel
Error	6	Invalid token ';' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	54	105	KeycloakIdentityModel
Error	8	Invalid token '{' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	12	9	KeycloakIdentityModel
Error	9	Invalid token '{' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	14	13	KeycloakIdentityModel
Error	7	Invalid token '=' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	11	77	KeycloakIdentityModel
Error	10	Invalid token '=' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimLookup.cs	14	59	KeycloakIdentityModel
Error	13	Invalid token '=' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	15	27	KeycloakIdentityModel
Error	15	Invalid token '=' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	16	30	KeycloakIdentityModel
Error	31	Invalid token '=' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Models\Configuration\DefaultKeycloakParameters.cs	75	67	KeycloakIdentityModel
Error	33	Invalid token '=' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Models\Configuration\DefaultKeycloakParameters.cs	84	55	KeycloakIdentityModel
Error	34	Invalid token '=' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Models\Configuration\DefaultKeycloakParameters.cs	92	59	KeycloakIdentityModel
Error	35	Invalid token '=' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Models\Configuration\DefaultKeycloakParameters.cs	100	61	KeycloakIdentityModel
Error	36	Invalid token '=' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Models\Configuration\DefaultKeycloakParameters.cs	108	54	KeycloakIdentityModel
Error	38	Invalid token '=' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Models\Configuration\DefaultKeycloakParameters.cs	120	60	KeycloakIdentityModel
Error	39	Invalid token '=' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Models\Configuration\DefaultKeycloakParameters.cs	129	63	KeycloakIdentityModel
Error	11	Invalid token '=>' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimLookup.cs	14	67	KeycloakIdentityModel
Error	5	Invalid token '>' in class, struct, or interface member declaration	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	54	91	KeycloakIdentityModel
Error	41	Metadata file 'C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\bin\Debug\KeycloakIdentityModel.dll' could not be found	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\Owin.Security.Keycloak\CSC	Owin.Security.Keycloak
Error	42	Metadata file 'C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\Owin.Security.Keycloak\bin\Debug\Owin.Security.Keycloak.dll' could not be found	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\SampleKeycloakApp\CSC	SampleKeycloakApp
Error	43	Property or indexer 'KeycloakIdentityModel.Utilities.OidcDataManager.Authority' cannot be assigned to -- it is read only	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\OidcDataManager.cs	33	13	KeycloakIdentityModel
Error	44	Property or indexer 'KeycloakIdentityModel.Utilities.OidcDataManager.MetadataEndpoint' cannot be assigned to -- it is read only	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\OidcDataManager.cs	34	13	KeycloakIdentityModel
Error	45	Property or indexer 'KeycloakIdentityModel.Utilities.OidcDataManager.TokenValidationEndpoint' cannot be assigned to -- it is read only	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\OidcDataManager.cs	35	13	KeycloakIdentityModel
Error	57	The call is ambiguous between the following methods or properties: 'System.Threading.Tasks.Task.Run<System.Security.Claims.ClaimsIdentity>(System.Func<System.Threading.Tasks.Task<System.Security.Claims.ClaimsIdentity>>)' and 'System.Threading.Tasks.Task.Run(System.Action)'	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	127	20	KeycloakIdentityModel
Error	48	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	39	69	KeycloakIdentityModel
Error	53	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	82	64	KeycloakIdentityModel
Error	54	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	93	65	KeycloakIdentityModel
Error	55	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	104	64	KeycloakIdentityModel
Error	56	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	117	64	KeycloakIdentityModel
Error	58	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	170	69	KeycloakIdentityModel
Error	59	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	171	67	KeycloakIdentityModel
Error	60	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	184	69	KeycloakIdentityModel
Error	61	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	185	65	KeycloakIdentityModel
Error	62	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	204	69	KeycloakIdentityModel
Error	63	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	205	66	KeycloakIdentityModel
Error	64	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	219	69	KeycloakIdentityModel
Error	65	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	220	67	KeycloakIdentityModel
Error	66	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	221	66	KeycloakIdentityModel
Error	67	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	239	69	KeycloakIdentityModel
Error	68	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	240	70	KeycloakIdentityModel
Error	70	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	265	69	KeycloakIdentityModel
Error	71	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	266	66	KeycloakIdentityModel
Error	72	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	286	69	KeycloakIdentityModel
Error	73	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	287	66	KeycloakIdentityModel
Error	74	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	302	69	KeycloakIdentityModel
Error	75	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	303	66	KeycloakIdentityModel
Error	76	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	304	70	KeycloakIdentityModel
Error	77	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	341	69	KeycloakIdentityModel
Error	78	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	345	49	KeycloakIdentityModel
Error	79	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	347	49	KeycloakIdentityModel
Error	80	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	351	49	KeycloakIdentityModel
Error	81	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	353	49	KeycloakIdentityModel
Error	82	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	355	49	KeycloakIdentityModel
Error	83	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	359	45	KeycloakIdentityModel
Error	84	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	362	45	KeycloakIdentityModel
Error	85	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	365	45	KeycloakIdentityModel
Error	88	The name 'nameof' does not exist in the current context	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\KeycloakIdentity.cs	460	66	KeycloakIdentityModel
Error	32	Type or namespace definition, or end-of-file expected	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\ClaimMapping\ClaimMappings.cs	80	9	KeycloakIdentityModel
Warning	46	The variable 'exception' is declared but never used	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\OidcDataManager.cs	146	40	KeycloakIdentityModel
Warning	47	The variable 'exception' is declared but never used	C:\Users\vramanathan\Downloads\KeycloakOwinAuthentication-master (1)\KeycloakOwinAuthentication-master\src\KeycloakIdentityModel\Utilities\OidcDataManager.cs	187	30	KeycloakIdentityModel

**Comment by dylanplecki** [comment] 2016-01-14 17:53
Huh, that's a weird error. Are you compiling from the source code, or are you using the NuGet packages in your own project? Also, what version of Visual Studio are you using and, if you're building your own project, what version of the .NET framework are you targeting? (that can be found in the project's properties page)

**Comment by dylanplecki** [comment] 2016-02-02 19:29
Potential fix: Use Visual Studio 2015+ since the project requires C# 6.0+ compiler support in order to compile. Otherwise, the NuGet packages listed will work on any platform with .NET 4.5+ target support enabled.

**Comment by dylanplecki** [comment] 2016-02-02 19:30
Seeing as this issue has been dormant for over two weeks, and a potential fix has been posted, I'm going to close the issue on the stipulation that it may be re-opened at any time by the OP, given that the issue is still not resolved.

**Closed by dylanplecki** 2016-02-02 19:30 UTC
